site_name: Atanu MLKit
site_description: Machine Learning with Python

repo_url: https://github.com/playatanu/atanu-mlkit

theme:
  name: material
  features:
    - content.code.copy
  palette: 
    - scheme: slate
      toggle:
        icon: material/brightness-7 
        name: Switch to light mode

    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# extra_javascript:
#     - 'javascripts/removeCredits.js'

extra:
  generator: false
    
